Object Storage Integration
cancogen-virus-seq/singularity pull request #17
Opened 2021-08-11 14:13 UTC by lepsalex

This is pretty significant refactor, the goals were the following:
- componentize reusable functionality so that we can compose different archive build pipelines more efficiently (https://wiki.oicr.on.ca/display/OV/CanCoGen+Virus+Seq+Data+Portal#CanCoGenVirusSeqDataPortal-4.4.1DataDownloadandAggregation-HighLevel)
- drop the usage of Muse in favour of going straight object storage using the AWS SDK
- update the API to allow for downloading files from object storage based on `archiveId` or the latest "all" archive
- rework the all archive build process to immediately cancel when new events start coming in if mid-build
- have the archive build process check that it is not building a duplicate archive, more relevant for future set query but also very useful if we wanted to use the interval builder instead of the event-driven one

**NOTE: The app config has changed, we will need to update the deployment values**

2021-08-11 16:27 UTC, andricDu requested changes
Looks good, some minor stuff. 

Really don't like long chains of lambdas as it forces the reader to focus on the nitty gritty rather than the overall functional intent. Much prefer description method reference chaining.

2021-08-11 16:27 UTC, andricDu commented on src/main/java/org/cancogenvirusseq/singularity/components/InstantToArchiveBuildRequest.java
> +            source ->
why not used named methods here as references. That way the whole chain would read like prose.

2021-08-11 16:27 UTC, andricDu commented on src/main/java/org/cancogenvirusseq/singularity/components/hoc/InstantToArchiveBuildRequest.java
> +                    AggregationBuilders.max("lastUpdatedDate")
why not use a static constant for these names?

2021-08-11 16:27 UTC, andricDu commented on src/main/java/org/cancogenvirusseq/singularity/config/s3Client/S3ClientProperties.java
> +  private int multipartMinPartSize = 5 * 1024 * 1024;
As far as I can tell, you are not actually doing any multipart uploads?

2021-08-11 16:27 UTC, andricDu commented on src/main/java/org/cancogenvirusseq/singularity/repository/model/Archive.java
> +  private Integer numOfDownloads;
why is this nullable?

2021-08-11 20:09 UTC, lepsalex commented on src/main/java/org/cancogenvirusseq/singularity/repository/model/Archive.java
> +  private Integer numOfDownloads;
it always starts of at 0 which is the default

2021-08-12 15:34 UTC, jaserud approved these changes

2021-08-12 15:58 UTC, merged