TSV creation fails due to array fields #43
cancogen-virus-seq/singularity pull request #44
Opened 2022-08-16 15:37 UTC by lrivera-oicr

2022-08-16 16:10 UTC, caravinci requested changes
Some preliminary comments and general style nitpicking.

2022-08-16 16:10 UTC, caravinci commented on Jenkinsfile
> +                    branch 'arrays'
We won't need these once the branch is merged & deleted.
```suggestion
```

2022-08-16 16:10 UTC, caravinci commented on Jenkinsfile
> +                    branch 'arrays'
```suggestion
```

2022-08-16 16:10 UTC, caravinci commented on src/main/java/org/cancogenvirusseq/singularity/components/model/AnalysisDocument.java
> +
```suggestion
```

2022-08-16 16:10 UTC, caravinci commented on src/main/java/org/cancogenvirusseq/singularity/components/utils/TsvUtils.java
> +
```suggestion
```

2022-08-16 19:19 UTC, UmmulkiramR commented on src/main/java/org/cancogenvirusseq/singularity/components/model/AnalysisDocument.java
> +
JsonProcessingException in the AnalysisDocument class can be removed from the imports if not being used.

2022-08-16 19:24 UTC, UmmulkiramR requested changes

2022-08-16 19:24 UTC, UmmulkiramR commented on src/main/java/org/cancogenvirusseq/singularity/components/utils/TsvUtils.java
> +
That's good work! 
You can may be change the indentation in TsvUtils to 2 spaces as that is the standard followed.

2022-08-16 20:09 UTC, UmmulkiramR commented on src/main/java/org/cancogenvirusseq/singularity/components/utils/TsvUtils.java
> +
How about making the LIST_SEPARATOR configurable?

2022-08-17 15:16 UTC, lrivera-oicr commented on Jenkinsfile
> +                    branch 'arrays'
arrays branch removed from Jenkinsfile

2022-08-17 15:17 UTC, lrivera-oicr commented on src/main/java/org/cancogenvirusseq/singularity/components/utils/TsvUtils.java
> +
added indentation and LIST_SEPARATOR is now configurable from application.yaml  utils.tsvListSeparator property

2022-08-17 15:40 UTC, caravinci commented on src/main/java/org/cancogenvirusseq/singularity/components/model/AnalysisDocument.java
> +
```suggestion
```

2022-08-17 15:41 UTC, caravinci approved these changes
Ready to "Squash and Merge" 🚢

2022-08-17 15:58 UTC, merged